### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by RyannGalea** [brandonmcconnell/tailwindcss-members#1]
I get this error trying to include into my angular 17 app.

it was added via 
yarn add tailwindcss-members --dev

```

X [ERROR] Cannot find module 'C:\outbuild\angular\node_modules\tailwindcss-members\dist\index.cjs' [plugin angular-sass]

    node_modules/jiti/dist/jiti.js:1:253216:
      1 │ ...olved}}try{return nativeRequire.resolve(id,options)}catch(error)...
        ╵                                    ^

    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1180:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1168:15)
    at resolveExports (node:internal/modules/cjs/loader:590:14)
    at Module._findPath (node:internal/modules/cjs/loader:667:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:27)
    at Function.resolve (node:internal/modules/helpers:187:19)
    at _resolve (C:\outbuild\angular\node_modules\jiti\dist\jiti.js:1:251148)
    at jiti (C:\outbuild\angular\node_modules\jiti\dist\jiti.js:1:253746)
    at C:\outbuild\angular\tailwind.config.js:78:5
    at evalModule (C:\outbuild\angular\node_modules\jiti\dist\jiti.js:1:256443)

  This error came from the "onLoad" callback registered here:

    node_modules/@angular-devkit/build-angular/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.js:131:22:
      131 │                 build.onLoad({ filter: language.fileFilter }, (0,...
          ╵                       ~~~~~~

    at setup (C:\outbuild\angular\node_modules\@angular-devkit\build-angular\src\tools\esbuild\stylesheets\stylesheet-plugin-factory.js:131:23)
    at async handlePlugins (C:\outbuild\angular\node_modules\esbuild\lib\main.js:1340:9)

  The plugin "angular-sass" was triggered by this import

    angular:styles/global:styles:1:8:
      1 │ @import './src/styles.scss';
        ╵         ~~~~~~~~~~~~~~~~~~~
```

![image](https://github.com/brandonmcconnell/tailwindcss-members/assets/18360468/29fedf42-939a-436c-9fc7-8e758e76e8eb)

![image](https://github.com/brandonmcconnell/tailwindcss-members/assets/18360468/8f6108f2-c7ac-4f58-bf09-3795015dfe6c)

I guess it should be noted that my config is also being wrapped with an animations package, not sure this would effect it or not as it made no different when I removed it and tried it just raw.

![image](https://github.com/brandonmcconnell/tailwindcss-members/assets/18360468/b25e154d-1daf-4619-83b8-56d8b83f6c59)

**Comment by brandonmcconnell** [comment]
@RyannGalea Can you update to `@latest` and see if that resolves the issue? I need to add a Git action that builds the package dist and npm deploys for me so I don't forget that step. Thanks for the report!

**Comment by RyannGalea** [comment]
@brandonmcconnell seems to load now without an issue.

**Comment by brandonmcconnell** [comment]
Great! Thanks again for the report @RyannGalea 🙂
